[connections.gsheets]
type = "service_account"
project_id = "project-polymer-program"
private_key_id ="64313c671faeb5fc5dae0b2f01d395e19e04734c"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMvl4yHj5YM6g+\nwwJUfsWde4e2HapOneXZ6R+7Z1+KB9LHG+z8YQKQGgF3q1TYcLRbuUcFiuwKotRV\nysSs4eUNtqkmJlNcCOgZSRpGbe+zJCA37QyN6fjh5D9FLquQh5m5Do8+Sl52yQ2Z\nhoeiu+rnJ/U/+mlPt9LwDFvYr2DAE16EFBWveSSXwQTjjuTH/zGjhU/4RiShEhu2\nAJ32huTXYeYrpTWmbDRY8deJCpA2L4zkjx0FsUWbh5X8E+SZes/75gfnU46n/RXp\n/SWeDQ3+28DGzaMDmy1CpQBsGiEYhzNQqmLn7sXfHsB5dXalCOiDghzTJbt8IY9j\nAODctEQNAgMBAAECggEAF2rYQOYD0QidSn4HXfgu2K5UTQKgEs8WTpzJfRSs0opN\nMXhNxMs+UiwliNv+tLmB5M4NyVgNQJLJmhGwCiTWx+KXv8N6NLK9rXFamBPUIV4W\nJz//igA/OxSPS2tBu/034FDSGBbnI0P+CYiW+kZihf4Bwhif25X2GJ8xy/qYMjT3\nmoIBhQXGzyZlItKJ2uwVwEF/YfNmtPb8wn8Fjp5BfYMWK7Du3/5EQiGaMcyH8TXj\nn4KFiSd/1QdyVxDqf3e2pQQZVj4q4FO7Zfu6JZNNIkvzJ8GOdelllaJxf0ZY4daA\nE2z3j5vIQ7bEJ9+Z9yFAYLVb/7c8gqubm1iGnx+l2QKBgQDFg49JvrbcoMZUAcT/\nt6PiMbzRmgodDvkv0giyProhwdMOMiR0jaL1p/QiIMlKG1KP2rw0n39ux3G3IY2B\nUXbghMquPC3JbrOZKz3bKED/ZcyWSRPyTzdumVTzB6n1PkmmU2N2vSdxc5n7kD3n\nsErZf1IzwwMTToI1e/vjyGRm9QKBgQC2a13CbPsfgnUriGzGTdCykwbZ9BOBId9Q\nrZJAg4/WIqyLMrJRmBlZQhIqyIL4A7UBR0KO0XjvGOPlkVjDtFVr9vgUU6p7yx/J\nZIoZuHGiz/Ja19xTWslskrEfADrZ5UECf/GQ526zbQy+4sc8cLzHawXgLNkjlnNj\nw43iXWJJuQKBgQC0WCu9aiYNzb9JdVQrKcK6BjAiMkSJw+JDh8Po/N13dUMA80fW\nJH1nULPZdZZV1BzOvSqb4ga5X+K1FC3gpkGlP5rQ/KHSCwJyGMmiEl9G0+y6TH+q\nACrdEaQ/RAArrXQSKpHnGU+qh6NRz6K2qoGtllO4b5efSVAbBdo5YgBLAQKBgQCU\nJ7E3lmGCnubg22VUzaBhWG4pGEW7DDKeCMqOoQtyJCk0yJDxGfIEf1fX7ZAJNKGO\njzysV867ieCV860/DTiPfj7P63+8GSYQ4BoVd6q7S96PD2A/Rq3vA1jdT8d8buiU\nyir8wCo1iazfX7nnCb0YzYAxKNuWPrwq24lhvuxz6QKBgATD6/JrCn0HDMSthzi0\nfJnOu6WF0k+M44LD8LveqbMbjOX0z0AMXHmTAR9Ba4VA4HHINPykxcesKsaqArJ1\n4ODuShCwr3m0sr/AS8sQ9Y1LRdCc+MHGPwqIlv5ho/V50HFd9PiUpW1j1EGWYmnc\nRVkywt4CFQDL2uHFzY73nO7E\n-----END PRIVATE KEY-----\n"
client_email = "service-acc@project-polymer-program.iam.gserviceaccount.com"
client_id = "109383878974076697249"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-acc%40project-polymer-program.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[file_address]
JSON_FILE_ID = "1lW8O7d-jdrp0WiRg3Uwm7qfkGrQvY7uD"
SPREADSHEET_URL = "https://docs.google.com/spreadsheets/d/18sGa7-DQ0v0oHpMesTySUjr9Z4dh70hr4PUNm6t3uo0/"
WORKSHEET_SALES = "RawSales"
WORKSHEET_CMR = "CMRData"
WORKSHEET_GROUP = "CustGroup"
WORKSHEET_MOU = "MOUData"
INVENTORY_SHEET_URL = "https://docs.google.com/spreadsheets/d/10zgl3NyAXSpMNvPbpcztD6Cw_Zd6wfhCw0Pi2iBDITc/"
WORKSHEET_AHMD_INVENTORY = "Daily Inventory"

[passwords]
admin = "zGjhU$78u"
user1 = "4RiS$hEhu2"
urer2 = "AS8sQ9Y1LRdCc"
user3 = "18sGa7"

[pricing]
PUBLISHED_DISCOUNT_MASTER_SHEET = "https://docs.google.com/spreadsheets/d/1Z5qAd8kGlvGTcgdXeBkB1mgxaWouCvtlzO9cwe---uY/"
UNPUBLISHED_DISCOUNT_MASTER_SHEET = "https://docs.google.com/spreadsheets/d/1k7hH_mx2kpzF2MCf-uuofwArbScEo248BFxFotiymr8/"
GROUP_MASTER_SHEET = "https://docs.google.com/spreadsheets/d/1APXjE_a9VrsJhRhdxdINZntVfwmYEWUZHFVrzNpNQ7s/"

OPAL_PE_PLANT = "https://docs.google.com/spreadsheets/d/1WJJXvfNhBxJUuzOPqxKIxfr6JWWhYaE64T7Kaap4Ndg/"
OPAL_PP_PLANT = "https://docs.google.com/spreadsheets/d/1XU29o31pk7sMuAeR58obISt7IWGzguigTBdtAeDBMJo/"
OPAL_PE_DEPOT = "https://docs.google.com/spreadsheets/d/19gLqyfa9_j_43hGqLmlcZKNaBxPT1bgxueGARE95Lz0/"
OPAL_PP_DEPOT = "https://docs.google.com/spreadsheets/d/1HyxbrTEEgq_Ttyscm274WCGjDnsz9jtg7rjAbZBxDCI/"
OPAL_FREIGHT = "https://docs.google.com/spreadsheets/d/1CYqcec3ZqYJTvDl-XBpVJDqEC8ppL_RWDPt-stdQExQ/"

HMEL_PE_PLANT = "https://docs.google.com/spreadsheets/d/1uVp7-8pjvCnAz5urQ1YKnNzT46ycgl4xrDV-UZFn_is/"
HMEL_PP_PLANT = "https://docs.google.com/spreadsheets/d/1RkjgU6WgRORYX64VmrJWbEGE80VmeMoDi0MoiOXvT2A/"
HMEL_PE_DEPOT = "https://docs.google.com/spreadsheets/d/1uVP7T4mkS1KI5Tt5WGby1F2XnCYNWfICxG9pGRaKRZQ/"
HMEL_PP_DEPOT = "https://docs.google.com/spreadsheets/d/1K4Od2UDdmND2S2Czua4oHWR5Udi1xJNdu9ad8iHL6aE/"
HMEL_FREIGHT = "https://docs.google.com/spreadsheets/d/17UOCowLCnQ5YfM0dTQpoTflvFRZ6CU2f1yIjBJdNKsA/"

IOCL_PE_PLANT = "https://docs.google.com/spreadsheets/d/1z8vyoDtZGUnTkDEQJxdbFljOOaLaFPcBzm159M5gUw0/"
IOCL_PE_DEPOT = "https://docs.google.com/spreadsheets/d/1_UWCGC9e7Ba69o4_Mz54QOy8A8PecuUxMrmQsFWZFzA/"
IOCL_PE_WAREHOUSE = "https://docs.google.com/spreadsheets/d/1ChyU4-Ew3JvmB5b2PDqE8hRQCDzahLswwjbsRA2oyAQ/"
IOCL_PP_PLANT = "https://docs.google.com/spreadsheets/d/1rL1wT_LE4euVC19JdOFN3j-eMMCKxaMS4C36XiIq0WQ/"
IOCL_PP_DEPOT = "https://docs.google.com/spreadsheets/d/1INEhS-tPPli9sggJrElklUXro9lVBJRaYQVuMCfSQuo/"
IOCL_PP_WAREHOUSE = "https://docs.google.com/spreadsheets/d/1JTNss4VNzcVybTbPsh-CWdQrQTQbgB_gA4YKRJy7kGY/"

GAIL_PE_DEPOT = "https://docs.google.com/spreadsheets/d/1LWYYHJ6Sxl2lKeqrBHvZ6aBuEWG2gSCsyXVJ9ZVD3hE/"
GAIL_PE_PLANT = "https://docs.google.com/spreadsheets/d/14WcQzfd7t3i3o--u4OgSeTZvRHLZBvjTJzqqDyZWNCU/"

NAYARA_PP_PLANT = "https://docs.google.com/spreadsheets/d/17z72TB8Ratj-GiAI7rix3OGdz4Eo1Pbw3lGkxf6pdK0/"
NAYARA_PP_DEPOT = "https://docs.google.com/spreadsheets/d/1wduGAXzE2fbj4Ppyl0VB4VFEzJkmaWZ-lKniesftAqs/"
NAYARA_FREIGHT = "https://docs.google.com/spreadsheets/d/1TbtkD1jm2obp8lj1FcEiWA2SA3USwsSrwQ5ttjrl_7I/"

MRPL_PP_PLANT = "https://docs.google.com/spreadsheets/d/1zO0FvWCIdIBqf3kjBtqFZIzWVlYWl2YpHmBCTOjlPCY/"
MRPL_PP_DEPOT = "https://docs.google.com/spreadsheets/d/1RqlBEAPo6Htut48x9opf0RPrf5OJBF2iDfd4sh0BaPY/"
MRPL_FREIGHT = "https://docs.google.com/spreadsheets/d/1hdguwHuVSy_70_B2fOrTeWhXUW7bhDPORatxM6OFVfk/"

RIL_PE_PLANT = "https://docs.google.com/spreadsheets/d/1wqQpCa2yLpUJsGd9pL_3O42-Gl8QqNWSSAoPvyJdUOs/"
RIL_PE_DEPOT = "https://docs.google.com/spreadsheets/d/1EYYcIV_34u3mFlPArXNXMns4VTOjJtwgz8_RB01HxmU/"
RIL_PP_PLANT = "https://docs.google.com/spreadsheets/d/19-0sSHy1b736DWr380E7wYFOQO-DXNqRmGGmPamYdPw/"
RIL_PP_DEPOT = "https://docs.google.com/spreadsheets/d/1Lv_y05dCMrfylU3fbIhZwmZ9SmPWc-LnELT0NsV67Hw/"

HPL_PE_PLANT = "https://docs.google.com/spreadsheets/d/1J-84opVy14IwQfl8R8vrhGIP45Yb2YqiLgPZ9ZjPSJQ/"
HPL_PE_DEPOT = "https://docs.google.com/spreadsheets/d/1D7NQ0cBE9_qpnN-66hICO0CtfP_VZnQc3LLVo5ee6t8/"
HPL_PP_PLANT = "https://docs.google.com/spreadsheets/d/16e6ERcsgFel-DC9UruT9LWH5pe23eRlbwp1qntIXOC8/"
HPL_PP_DEPOT = "https://docs.google.com/spreadsheets/d/1Wq1a4fUvc_1J-C3hPxaoHznq7t64SJ9XleKFKH7p68Q/"
HPL_FREIGHT = "https://docs.google.com/spreadsheets/d/1Bq_ag0BFyCORpufc9cv4N_XjyvppzeAmLWD6M3U1pI8/"

HPCL_PP_DEPOT = "https://docs.google.com/spreadsheets/d/1qj4ASbD0sQPWo80dTCmPcqaW8-_pzfZ1zcXqbbJMM6U/"
HPCL_PE_DEPOT = "https://docs.google.com/spreadsheets/d/1UWXJpkLYvEYc2W83s9d71smgnVU_MZNRU8aVTDOsZKQ/"